/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'jewellery' : JewelleryCategory } |
  { 'fashion' : FashionCategory };
export type FashionCategory = { 'kurtaKurtis' : null } |
  { 'sarees' : null } |
  { 'festive' : null } |
  { 'gowns' : null } |
  { 'salwarSuits' : null } |
  { 'sportsWear' : null } |
  { 'lehengaCholis' : null } |
  { 'westernWear' : null };
export type JewelleryCategory = { 'necklaces' : null } |
  { 'rings' : null };
export interface Product {
  'id' : bigint,
  'mrp' : bigint,
  'title' : string,
  'description' : string,
  'imageUrl' : string,
  'isFeatured' : boolean,
  'category' : Category,
  'affiliateLink' : string,
  'price' : bigint,
  'discountPercentage' : bigint,
}
export interface _SERVICE {
  'addProduct' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      bigint,
      bigint,
      bigint,
      Category,
      boolean,
    ],
    Product
  >,
  'adminLogin' : ActorMethod<[string, string], [] | [string]>,
  'changeAdminCredentials' : ActorMethod<[string, string, string], boolean>,
  'deleteProduct' : ActorMethod<[string, bigint], undefined>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'updateProduct' : ActorMethod<
    [
      string,
      bigint,
      string,
      string,
      string,
      string,
      bigint,
      bigint,
      bigint,
      Category,
      boolean,
    ],
    Product
  >,
  'validateAdminToken' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];