/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const JewelleryCategory = IDL.Variant({
  'necklaces' : IDL.Null,
  'rings' : IDL.Null,
});
export const FashionCategory = IDL.Variant({
  'kurtaKurtis' : IDL.Null,
  'sarees' : IDL.Null,
  'festive' : IDL.Null,
  'gowns' : IDL.Null,
  'salwarSuits' : IDL.Null,
  'sportsWear' : IDL.Null,
  'lehengaCholis' : IDL.Null,
  'westernWear' : IDL.Null,
});
export const Category = IDL.Variant({
  'jewellery' : JewelleryCategory,
  'fashion' : FashionCategory,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'mrp' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'category' : Category,
  'affiliateLink' : IDL.Text,
  'price' : IDL.Nat,
  'discountPercentage' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        Category,
        IDL.Bool,
      ],
      [Product],
      [],
    ),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(IDL.Text)], []),
  'changeAdminCredentials' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'deleteProduct' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'updateProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        Category,
        IDL.Bool,
      ],
      [Product],
      [],
    ),
  'validateAdminToken' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const JewelleryCategory = IDL.Variant({
    'necklaces' : IDL.Null,
    'rings' : IDL.Null,
  });
  const FashionCategory = IDL.Variant({
    'kurtaKurtis' : IDL.Null,
    'sarees' : IDL.Null,
    'festive' : IDL.Null,
    'gowns' : IDL.Null,
    'salwarSuits' : IDL.Null,
    'sportsWear' : IDL.Null,
    'lehengaCholis' : IDL.Null,
    'westernWear' : IDL.Null,
  });
  const Category = IDL.Variant({
    'jewellery' : JewelleryCategory,
    'fashion' : FashionCategory,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'mrp' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'category' : Category,
    'affiliateLink' : IDL.Text,
    'price' : IDL.Nat,
    'discountPercentage' : IDL.Nat,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          Category,
          IDL.Bool,
        ],
        [Product],
        [],
      ),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(IDL.Text)], []),
    'changeAdminCredentials' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'deleteProduct' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'updateProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          Category,
          IDL.Bool,
        ],
        [Product],
        [],
      ),
    'validateAdminToken' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };