/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Category = {
    __kind__: "jewellery";
    jewellery: JewelleryCategory;
} | {
    __kind__: "fashion";
    fashion: FashionCategory;
};
export interface Product {
    id: bigint;
    mrp: bigint;
    title: string;
    description: string;
    imageUrl: string;
    isFeatured: boolean;
    category: Category;
    affiliateLink: string;
    price: bigint;
    discountPercentage: bigint;
}
export enum FashionCategory {
    kurtaKurtis = "kurtaKurtis",
    sarees = "sarees",
    festive = "festive",
    gowns = "gowns",
    salwarSuits = "salwarSuits",
    sportsWear = "sportsWear",
    lehengaCholis = "lehengaCholis",
    westernWear = "westernWear"
}
export enum JewelleryCategory {
    necklaces = "necklaces",
    rings = "rings"
}
export interface backendInterface {
    addProduct(token: string, title: string, description: string, imageUrl: string, affiliateLink: string, price: bigint, mrp: bigint, discountPercentage: bigint, category: Category, isFeatured: boolean): Promise<Product>;
    adminLogin(username: string, password: string): Promise<string | null>;
    changeAdminCredentials(token: string, newUsername: string, newPassword: string): Promise<boolean>;
    deleteProduct(token: string, id: bigint): Promise<void>;
    getAllProducts(): Promise<Array<Product>>;
    updateProduct(token: string, id: bigint, title: string, description: string, imageUrl: string, affiliateLink: string, price: bigint, mrp: bigint, discountPercentage: bigint, category: Category, isFeatured: boolean): Promise<Product>;
    validateAdminToken(token: string): Promise<boolean>;
}
import type { Category as _Category, FashionCategory as _FashionCategory, JewelleryCategory as _JewelleryCategory, Product as _Product } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addProduct(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint, arg6: bigint, arg7: bigint, arg8: Category, arg9: boolean): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg8), arg9);
                return from_candid_Product_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg8), arg9);
            return from_candid_Product_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminLogin(arg0: string, arg1: string): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0, arg1);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0, arg1);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async changeAdminCredentials(arg0: string, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.changeAdminCredentials(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.changeAdminCredentials(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteProduct(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0, arg1);
            return result;
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProduct(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: string, arg5: string, arg6: bigint, arg7: bigint, arg8: bigint, arg9: Category, arg10: boolean): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg9), arg10);
                return from_candid_Product_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, to_candid_Category_n1(this._uploadFile, this._downloadFile, arg9), arg10);
            return from_candid_Product_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async validateAdminToken(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.validateAdminToken(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateAdminToken(arg0);
            return result;
        }
    }
}
function from_candid_Category_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_FashionCategory_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FashionCategory): FashionCategory {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_JewelleryCategory_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JewelleryCategory): JewelleryCategory {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    mrp: bigint;
    title: string;
    description: string;
    imageUrl: string;
    isFeatured: boolean;
    category: _Category;
    affiliateLink: string;
    price: bigint;
    discountPercentage: bigint;
}): {
    id: bigint;
    mrp: bigint;
    title: string;
    description: string;
    imageUrl: string;
    isFeatured: boolean;
    category: Category;
    affiliateLink: string;
    price: bigint;
    discountPercentage: bigint;
} {
    return {
        id: value.id,
        mrp: value.mrp,
        title: value.title,
        description: value.description,
        imageUrl: value.imageUrl,
        isFeatured: value.isFeatured,
        category: from_candid_Category_n9(_uploadFile, _downloadFile, value.category),
        affiliateLink: value.affiliateLink,
        price: value.price,
        discountPercentage: value.discountPercentage
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    jewellery: _JewelleryCategory;
} | {
    fashion: _FashionCategory;
}): {
    __kind__: "jewellery";
    jewellery: JewelleryCategory;
} | {
    __kind__: "fashion";
    fashion: FashionCategory;
} {
    return "jewellery" in value ? {
        __kind__: "jewellery",
        jewellery: from_candid_JewelleryCategory_n11(_uploadFile, _downloadFile, value.jewellery)
    } : "fashion" in value ? {
        __kind__: "fashion",
        fashion: from_candid_FashionCategory_n13(_uploadFile, _downloadFile, value.fashion)
    } : value;
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    necklaces: null;
} | {
    rings: null;
}): JewelleryCategory {
    return "necklaces" in value ? JewelleryCategory.necklaces : "rings" in value ? JewelleryCategory.rings : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    kurtaKurtis: null;
} | {
    sarees: null;
} | {
    festive: null;
} | {
    gowns: null;
} | {
    salwarSuits: null;
} | {
    sportsWear: null;
} | {
    lehengaCholis: null;
} | {
    westernWear: null;
}): FashionCategory {
    return "kurtaKurtis" in value ? FashionCategory.kurtaKurtis : "sarees" in value ? FashionCategory.sarees : "festive" in value ? FashionCategory.festive : "gowns" in value ? FashionCategory.gowns : "salwarSuits" in value ? FashionCategory.salwarSuits : "sportsWear" in value ? FashionCategory.sportsWear : "lehengaCholis" in value ? FashionCategory.lehengaCholis : "westernWear" in value ? FashionCategory.westernWear : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n7(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_FashionCategory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FashionCategory): _FashionCategory {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_JewelleryCategory_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JewelleryCategory): _JewelleryCategory {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "jewellery";
    jewellery: JewelleryCategory;
} | {
    __kind__: "fashion";
    fashion: FashionCategory;
}): {
    jewellery: _JewelleryCategory;
} | {
    fashion: _FashionCategory;
} {
    return value.__kind__ === "jewellery" ? {
        jewellery: to_candid_JewelleryCategory_n5(_uploadFile, _downloadFile, value.jewellery)
    } : value.__kind__ === "fashion" ? {
        fashion: to_candid_FashionCategory_n3(_uploadFile, _downloadFile, value.fashion)
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FashionCategory): {
    kurtaKurtis: null;
} | {
    sarees: null;
} | {
    festive: null;
} | {
    gowns: null;
} | {
    salwarSuits: null;
} | {
    sportsWear: null;
} | {
    lehengaCholis: null;
} | {
    westernWear: null;
} {
    return value == FashionCategory.kurtaKurtis ? {
        kurtaKurtis: null
    } : value == FashionCategory.sarees ? {
        sarees: null
    } : value == FashionCategory.festive ? {
        festive: null
    } : value == FashionCategory.gowns ? {
        gowns: null
    } : value == FashionCategory.salwarSuits ? {
        salwarSuits: null
    } : value == FashionCategory.sportsWear ? {
        sportsWear: null
    } : value == FashionCategory.lehengaCholis ? {
        lehengaCholis: null
    } : value == FashionCategory.westernWear ? {
        westernWear: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JewelleryCategory): {
    necklaces: null;
} | {
    rings: null;
} {
    return value == JewelleryCategory.necklaces ? {
        necklaces: null
    } : value == JewelleryCategory.rings ? {
        rings: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
